### ISSUE TITLE
EntityInheritence does not work

### ISSUE THREAD

**Issue by stmfcgcg** [benjamin658/typeorm-cursor-pagination#18]
if I have fields defined in a base class, the pagination fails with an error:

Unhandled Exception TypeError: Cannot read property 'name' of undefined
    at Paginator.getEntityPropertyType (/var/task/node_modules/typeorm-cursor-pagination/src/Paginator.ts:196:77)
    at /var/task/node_modules/typeorm-cursor-pagination/src/Paginator.ts:174:25
    at Array.map (<anonymous>)
    at Paginator.encode (/var/task/node_modules/typeorm-cursor-pagination/src/Paginator.ts:173:41)
    at Paginator.<anonymous> (/var/task/node_modules/typeorm-cursor-pagination/src/Paginator.ts:90:35)
    at Generator.next (<anonymous>)
    at fulfilled (/var/task/node_modules/typeorm-cursor-pagination/lib/Paginator.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

The code fails because:

  private getEntityPropertyType(key: string): string {
    return Reflect.getOwnMetadata('design:type', this.entity.prototype, key).name.toLowerCase();
  }

When encoding the data, the algorithm only looks at fields in the current class and not those that are inherited

**Comment by benjamin658** [comment]
Hi @stmfcgcg ,

This issue has been fixed in v0.4.1 release, please upgrade the module.

Thanks.
