### ISSUE TITLE
Joins Not Working with Paginator

### ISSUE THREAD

**Issue by steveroseik** [benjamin658/typeorm-cursor-pagination#83]
this is a normal query join that works fine:

` const res = await this.repo.createQueryBuilder('courierSheet')
    .leftJoinAndSelect('courierSheet.sheetOrders', 'sheetOrders').execute();`

This is paginator code:
    
    ` const queryBuilder = this.repo.createQueryBuilder('courierSheet')
    .leftJoinAndSelect('courierSheet.sheetOrders', 'sheetOrders');

    const paginator = buildPaginator({
      entity: CourierSheet,
      paginationKeys: ['id'],
      query: {
        limit: input.limit,
        order: input.isAsc ? 'ASC' : 'DESC',
        beforeCursor: input.beforeCursor,
        afterCursor: input.afterCursor
      }
    })
    return paginator.paginate(queryBuilder);`

 **when I try to execute it with paginator I get error:**
    
    `TypeORMError: "couriersheet" alias was not found. Maybe you forgot to join it?
    at QueryExpressionMap.findAliasByName (/Users/roseik/js-projects/greenline_server/src/query-builder/QueryExpressionMap.ts:448:19)
    at /Users/roseik/js-projects/greenline_server/src/query-builder/SelectQueryBuilder.ts:3674:54
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/Users/roseik/js-projects/greenline_server/src/query-builder/SelectQueryBuilder.ts:3669:14)
    at SelectQueryBuilder.executeEntitiesAndRawResults (/Users/roseik/js-projects/greenline_server/src/query-builder/SelectQueryBuilder.ts:3429:22)
    at SelectQueryBuilder.getRawAndEntities (/Users/roseik/js-projects/greenline_server/src/query-builder/SelectQueryBuilder.ts:1670:40)
    at SelectQueryBuilder.getMany (/Users/roseik/js-projects/greenline_server/src/query-builder/SelectQueryBuilder.ts:1760:36)
    at Paginator.<anonymous> (/Users/roseik/js-projects/greenline_server/node_modules/typeorm-cursor-pagination/src/Paginator.ts:81:60)
    at Generator.next (<anonymous>)
    at /Users/roseik/js-projects/greenline_server/node_modules/typeorm-cursor-pagination/lib/Paginator.js:8:71`

**Comment by Avetik666** [comment]
I think the issue is not with the join but rather with the fact that courierSheet is used as couriersheet so it automatically does toLowerCase() I think which breaks the query. I have the exact same issue

**Comment by Avetik666** [comment]
Found the solution

const paginator = buildPaginator({
  entity: CourierSheet,
  alias: 'courierSheet',
  paginationKeys: ['id'],
  query: {
    limit: input.limit,
    order: input.isAsc ? 'ASC' : 'DESC',
    beforeCursor: input.beforeCursor,
    afterCursor: input.afterCursor
  }
})

just add the alias and it will work
